[package]
name = "gasless"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
stylus-sdk = { version = "0.10", features = ["hostio"] }
alloy-primitives = "1.3"
alloy-sol-types = "1.3"

[features]
export-abi = ["stylus-sdk/export-abi"]

[[bin]]
name = "gasless"
path = "src/main.rs"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true
